qsub -q "all2.q" -e /home/atzmonm/data/runs/0_\$TASK_ID.err -o /home/atzmonm/data/runs/0_\$TASK_ID.out ./runs/arrayruns0.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/1_\$TASK_ID.err -o /home/atzmonm/data/runs/1_\$TASK_ID.out ./runs/arrayruns1.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/2_\$TASK_ID.err -o /home/atzmonm/data/runs/2_\$TASK_ID.out ./runs/arrayruns2.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/3_\$TASK_ID.err -o /home/atzmonm/data/runs/3_\$TASK_ID.out ./runs/arrayruns3.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/4_\$TASK_ID.err -o /home/atzmonm/data/runs/4_\$TASK_ID.out ./runs/arrayruns4.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/5_\$TASK_ID.err -o /home/atzmonm/data/runs/5_\$TASK_ID.out ./runs/arrayruns5.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/6_\$TASK_ID.err -o /home/atzmonm/data/runs/6_\$TASK_ID.out ./runs/arrayruns6.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/7_\$TASK_ID.err -o /home/atzmonm/data/runs/7_\$TASK_ID.out ./runs/arrayruns7.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/8_\$TASK_ID.err -o /home/atzmonm/data/runs/8_\$TASK_ID.out ./runs/arrayruns8.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/9_\$TASK_ID.err -o /home/atzmonm/data/runs/9_\$TASK_ID.out ./runs/arrayruns9.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/10_\$TASK_ID.err -o /home/atzmonm/data/runs/10_\$TASK_ID.out ./runs/arrayruns10.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/11_\$TASK_ID.err -o /home/atzmonm/data/runs/11_\$TASK_ID.out ./runs/arrayruns11.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/12_\$TASK_ID.err -o /home/atzmonm/data/runs/12_\$TASK_ID.out ./runs/arrayruns12.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/13_\$TASK_ID.err -o /home/atzmonm/data/runs/13_\$TASK_ID.out ./runs/arrayruns13.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/14_\$TASK_ID.err -o /home/atzmonm/data/runs/14_\$TASK_ID.out ./runs/arrayruns14.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/15_\$TASK_ID.err -o /home/atzmonm/data/runs/15_\$TASK_ID.out ./runs/arrayruns15.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/16_\$TASK_ID.err -o /home/atzmonm/data/runs/16_\$TASK_ID.out ./runs/arrayruns16.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/17_\$TASK_ID.err -o /home/atzmonm/data/runs/17_\$TASK_ID.out ./runs/arrayruns17.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/18_\$TASK_ID.err -o /home/atzmonm/data/runs/18_\$TASK_ID.out ./runs/arrayruns18.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/19_\$TASK_ID.err -o /home/atzmonm/data/runs/19_\$TASK_ID.out ./runs/arrayruns19.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/20_\$TASK_ID.err -o /home/atzmonm/data/runs/20_\$TASK_ID.out ./runs/arrayruns20.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/21_\$TASK_ID.err -o /home/atzmonm/data/runs/21_\$TASK_ID.out ./runs/arrayruns21.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/22_\$TASK_ID.err -o /home/atzmonm/data/runs/22_\$TASK_ID.out ./runs/arrayruns22.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/23_\$TASK_ID.err -o /home/atzmonm/data/runs/23_\$TASK_ID.out ./runs/arrayruns23.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/24_\$TASK_ID.err -o /home/atzmonm/data/runs/24_\$TASK_ID.out ./runs/arrayruns24.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/25_\$TASK_ID.err -o /home/atzmonm/data/runs/25_\$TASK_ID.out ./runs/arrayruns25.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/26_\$TASK_ID.err -o /home/atzmonm/data/runs/26_\$TASK_ID.out ./runs/arrayruns26.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/27_\$TASK_ID.err -o /home/atzmonm/data/runs/27_\$TASK_ID.out ./runs/arrayruns27.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/28_\$TASK_ID.err -o /home/atzmonm/data/runs/28_\$TASK_ID.out ./runs/arrayruns28.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/29_\$TASK_ID.err -o /home/atzmonm/data/runs/29_\$TASK_ID.out ./runs/arrayruns29.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/30_\$TASK_ID.err -o /home/atzmonm/data/runs/30_\$TASK_ID.out ./runs/arrayruns30.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/31_\$TASK_ID.err -o /home/atzmonm/data/runs/31_\$TASK_ID.out ./runs/arrayruns31.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/32_\$TASK_ID.err -o /home/atzmonm/data/runs/32_\$TASK_ID.out ./runs/arrayruns32.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/33_\$TASK_ID.err -o /home/atzmonm/data/runs/33_\$TASK_ID.out ./runs/arrayruns33.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/34_\$TASK_ID.err -o /home/atzmonm/data/runs/34_\$TASK_ID.out ./runs/arrayruns34.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/35_\$TASK_ID.err -o /home/atzmonm/data/runs/35_\$TASK_ID.out ./runs/arrayruns35.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/36_\$TASK_ID.err -o /home/atzmonm/data/runs/36_\$TASK_ID.out ./runs/arrayruns36.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/37_\$TASK_ID.err -o /home/atzmonm/data/runs/37_\$TASK_ID.out ./runs/arrayruns37.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/38_\$TASK_ID.err -o /home/atzmonm/data/runs/38_\$TASK_ID.out ./runs/arrayruns38.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/39_\$TASK_ID.err -o /home/atzmonm/data/runs/39_\$TASK_ID.out ./runs/arrayruns39.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/40_\$TASK_ID.err -o /home/atzmonm/data/runs/40_\$TASK_ID.out ./runs/arrayruns40.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/41_\$TASK_ID.err -o /home/atzmonm/data/runs/41_\$TASK_ID.out ./runs/arrayruns41.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/42_\$TASK_ID.err -o /home/atzmonm/data/runs/42_\$TASK_ID.out ./runs/arrayruns42.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/43_\$TASK_ID.err -o /home/atzmonm/data/runs/43_\$TASK_ID.out ./runs/arrayruns43.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/44_\$TASK_ID.err -o /home/atzmonm/data/runs/44_\$TASK_ID.out ./runs/arrayruns44.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/45_\$TASK_ID.err -o /home/atzmonm/data/runs/45_\$TASK_ID.out ./runs/arrayruns45.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/46_\$TASK_ID.err -o /home/atzmonm/data/runs/46_\$TASK_ID.out ./runs/arrayruns46.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/47_\$TASK_ID.err -o /home/atzmonm/data/runs/47_\$TASK_ID.out ./runs/arrayruns47.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/48_\$TASK_ID.err -o /home/atzmonm/data/runs/48_\$TASK_ID.out ./runs/arrayruns48.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/49_\$TASK_ID.err -o /home/atzmonm/data/runs/49_\$TASK_ID.out ./runs/arrayruns49.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/50_\$TASK_ID.err -o /home/atzmonm/data/runs/50_\$TASK_ID.out ./runs/arrayruns50.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/51_\$TASK_ID.err -o /home/atzmonm/data/runs/51_\$TASK_ID.out ./runs/arrayruns51.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/52_\$TASK_ID.err -o /home/atzmonm/data/runs/52_\$TASK_ID.out ./runs/arrayruns52.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/53_\$TASK_ID.err -o /home/atzmonm/data/runs/53_\$TASK_ID.out ./runs/arrayruns53.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/54_\$TASK_ID.err -o /home/atzmonm/data/runs/54_\$TASK_ID.out ./runs/arrayruns54.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/55_\$TASK_ID.err -o /home/atzmonm/data/runs/55_\$TASK_ID.out ./runs/arrayruns55.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/56_\$TASK_ID.err -o /home/atzmonm/data/runs/56_\$TASK_ID.out ./runs/arrayruns56.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/57_\$TASK_ID.err -o /home/atzmonm/data/runs/57_\$TASK_ID.out ./runs/arrayruns57.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/58_\$TASK_ID.err -o /home/atzmonm/data/runs/58_\$TASK_ID.out ./runs/arrayruns58.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/59_\$TASK_ID.err -o /home/atzmonm/data/runs/59_\$TASK_ID.out ./runs/arrayruns59.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/60_\$TASK_ID.err -o /home/atzmonm/data/runs/60_\$TASK_ID.out ./runs/arrayruns60.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/61_\$TASK_ID.err -o /home/atzmonm/data/runs/61_\$TASK_ID.out ./runs/arrayruns61.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/62_\$TASK_ID.err -o /home/atzmonm/data/runs/62_\$TASK_ID.out ./runs/arrayruns62.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/63_\$TASK_ID.err -o /home/atzmonm/data/runs/63_\$TASK_ID.out ./runs/arrayruns63.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/64_\$TASK_ID.err -o /home/atzmonm/data/runs/64_\$TASK_ID.out ./runs/arrayruns64.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/65_\$TASK_ID.err -o /home/atzmonm/data/runs/65_\$TASK_ID.out ./runs/arrayruns65.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/66_\$TASK_ID.err -o /home/atzmonm/data/runs/66_\$TASK_ID.out ./runs/arrayruns66.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/67_\$TASK_ID.err -o /home/atzmonm/data/runs/67_\$TASK_ID.out ./runs/arrayruns67.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/68_\$TASK_ID.err -o /home/atzmonm/data/runs/68_\$TASK_ID.out ./runs/arrayruns68.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/69_\$TASK_ID.err -o /home/atzmonm/data/runs/69_\$TASK_ID.out ./runs/arrayruns69.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/70_\$TASK_ID.err -o /home/atzmonm/data/runs/70_\$TASK_ID.out ./runs/arrayruns70.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/71_\$TASK_ID.err -o /home/atzmonm/data/runs/71_\$TASK_ID.out ./runs/arrayruns71.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/72_\$TASK_ID.err -o /home/atzmonm/data/runs/72_\$TASK_ID.out ./runs/arrayruns72.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/73_\$TASK_ID.err -o /home/atzmonm/data/runs/73_\$TASK_ID.out ./runs/arrayruns73.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/74_\$TASK_ID.err -o /home/atzmonm/data/runs/74_\$TASK_ID.out ./runs/arrayruns74.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/75_\$TASK_ID.err -o /home/atzmonm/data/runs/75_\$TASK_ID.out ./runs/arrayruns75.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/76_\$TASK_ID.err -o /home/atzmonm/data/runs/76_\$TASK_ID.out ./runs/arrayruns76.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/77_\$TASK_ID.err -o /home/atzmonm/data/runs/77_\$TASK_ID.out ./runs/arrayruns77.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/78_\$TASK_ID.err -o /home/atzmonm/data/runs/78_\$TASK_ID.out ./runs/arrayruns78.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/79_\$TASK_ID.err -o /home/atzmonm/data/runs/79_\$TASK_ID.out ./runs/arrayruns79.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/80_\$TASK_ID.err -o /home/atzmonm/data/runs/80_\$TASK_ID.out ./runs/arrayruns80.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/81_\$TASK_ID.err -o /home/atzmonm/data/runs/81_\$TASK_ID.out ./runs/arrayruns81.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/82_\$TASK_ID.err -o /home/atzmonm/data/runs/82_\$TASK_ID.out ./runs/arrayruns82.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/83_\$TASK_ID.err -o /home/atzmonm/data/runs/83_\$TASK_ID.out ./runs/arrayruns83.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/84_\$TASK_ID.err -o /home/atzmonm/data/runs/84_\$TASK_ID.out ./runs/arrayruns84.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/85_\$TASK_ID.err -o /home/atzmonm/data/runs/85_\$TASK_ID.out ./runs/arrayruns85.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/86_\$TASK_ID.err -o /home/atzmonm/data/runs/86_\$TASK_ID.out ./runs/arrayruns86.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/87_\$TASK_ID.err -o /home/atzmonm/data/runs/87_\$TASK_ID.out ./runs/arrayruns87.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/88_\$TASK_ID.err -o /home/atzmonm/data/runs/88_\$TASK_ID.out ./runs/arrayruns88.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/89_\$TASK_ID.err -o /home/atzmonm/data/runs/89_\$TASK_ID.out ./runs/arrayruns89.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/90_\$TASK_ID.err -o /home/atzmonm/data/runs/90_\$TASK_ID.out ./runs/arrayruns90.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/91_\$TASK_ID.err -o /home/atzmonm/data/runs/91_\$TASK_ID.out ./runs/arrayruns91.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/92_\$TASK_ID.err -o /home/atzmonm/data/runs/92_\$TASK_ID.out ./runs/arrayruns92.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/93_\$TASK_ID.err -o /home/atzmonm/data/runs/93_\$TASK_ID.out ./runs/arrayruns93.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/94_\$TASK_ID.err -o /home/atzmonm/data/runs/94_\$TASK_ID.out ./runs/arrayruns94.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/95_\$TASK_ID.err -o /home/atzmonm/data/runs/95_\$TASK_ID.out ./runs/arrayruns95.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/96_\$TASK_ID.err -o /home/atzmonm/data/runs/96_\$TASK_ID.out ./runs/arrayruns96.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/97_\$TASK_ID.err -o /home/atzmonm/data/runs/97_\$TASK_ID.out ./runs/arrayruns97.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/98_\$TASK_ID.err -o /home/atzmonm/data/runs/98_\$TASK_ID.out ./runs/arrayruns98.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/99_\$TASK_ID.err -o /home/atzmonm/data/runs/99_\$TASK_ID.out ./runs/arrayruns99.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/100_\$TASK_ID.err -o /home/atzmonm/data/runs/100_\$TASK_ID.out ./runs/arrayruns100.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/101_\$TASK_ID.err -o /home/atzmonm/data/runs/101_\$TASK_ID.out ./runs/arrayruns101.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/102_\$TASK_ID.err -o /home/atzmonm/data/runs/102_\$TASK_ID.out ./runs/arrayruns102.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/103_\$TASK_ID.err -o /home/atzmonm/data/runs/103_\$TASK_ID.out ./runs/arrayruns103.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/104_\$TASK_ID.err -o /home/atzmonm/data/runs/104_\$TASK_ID.out ./runs/arrayruns104.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/105_\$TASK_ID.err -o /home/atzmonm/data/runs/105_\$TASK_ID.out ./runs/arrayruns105.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/106_\$TASK_ID.err -o /home/atzmonm/data/runs/106_\$TASK_ID.out ./runs/arrayruns106.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/107_\$TASK_ID.err -o /home/atzmonm/data/runs/107_\$TASK_ID.out ./runs/arrayruns107.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/108_\$TASK_ID.err -o /home/atzmonm/data/runs/108_\$TASK_ID.out ./runs/arrayruns108.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/109_\$TASK_ID.err -o /home/atzmonm/data/runs/109_\$TASK_ID.out ./runs/arrayruns109.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/110_\$TASK_ID.err -o /home/atzmonm/data/runs/110_\$TASK_ID.out ./runs/arrayruns110.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/111_\$TASK_ID.err -o /home/atzmonm/data/runs/111_\$TASK_ID.out ./runs/arrayruns111.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/112_\$TASK_ID.err -o /home/atzmonm/data/runs/112_\$TASK_ID.out ./runs/arrayruns112.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/113_\$TASK_ID.err -o /home/atzmonm/data/runs/113_\$TASK_ID.out ./runs/arrayruns113.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/114_\$TASK_ID.err -o /home/atzmonm/data/runs/114_\$TASK_ID.out ./runs/arrayruns114.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/115_\$TASK_ID.err -o /home/atzmonm/data/runs/115_\$TASK_ID.out ./runs/arrayruns115.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/116_\$TASK_ID.err -o /home/atzmonm/data/runs/116_\$TASK_ID.out ./runs/arrayruns116.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/117_\$TASK_ID.err -o /home/atzmonm/data/runs/117_\$TASK_ID.out ./runs/arrayruns117.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/118_\$TASK_ID.err -o /home/atzmonm/data/runs/118_\$TASK_ID.out ./runs/arrayruns118.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/119_\$TASK_ID.err -o /home/atzmonm/data/runs/119_\$TASK_ID.out ./runs/arrayruns119.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/120_\$TASK_ID.err -o /home/atzmonm/data/runs/120_\$TASK_ID.out ./runs/arrayruns120.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/121_\$TASK_ID.err -o /home/atzmonm/data/runs/121_\$TASK_ID.out ./runs/arrayruns121.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/122_\$TASK_ID.err -o /home/atzmonm/data/runs/122_\$TASK_ID.out ./runs/arrayruns122.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/123_\$TASK_ID.err -o /home/atzmonm/data/runs/123_\$TASK_ID.out ./runs/arrayruns123.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/124_\$TASK_ID.err -o /home/atzmonm/data/runs/124_\$TASK_ID.out ./runs/arrayruns124.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/125_\$TASK_ID.err -o /home/atzmonm/data/runs/125_\$TASK_ID.out ./runs/arrayruns125.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/126_\$TASK_ID.err -o /home/atzmonm/data/runs/126_\$TASK_ID.out ./runs/arrayruns126.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/127_\$TASK_ID.err -o /home/atzmonm/data/runs/127_\$TASK_ID.out ./runs/arrayruns127.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/128_\$TASK_ID.err -o /home/atzmonm/data/runs/128_\$TASK_ID.out ./runs/arrayruns128.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/129_\$TASK_ID.err -o /home/atzmonm/data/runs/129_\$TASK_ID.out ./runs/arrayruns129.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/130_\$TASK_ID.err -o /home/atzmonm/data/runs/130_\$TASK_ID.out ./runs/arrayruns130.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/131_\$TASK_ID.err -o /home/atzmonm/data/runs/131_\$TASK_ID.out ./runs/arrayruns131.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/132_\$TASK_ID.err -o /home/atzmonm/data/runs/132_\$TASK_ID.out ./runs/arrayruns132.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/133_\$TASK_ID.err -o /home/atzmonm/data/runs/133_\$TASK_ID.out ./runs/arrayruns133.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/134_\$TASK_ID.err -o /home/atzmonm/data/runs/134_\$TASK_ID.out ./runs/arrayruns134.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/135_\$TASK_ID.err -o /home/atzmonm/data/runs/135_\$TASK_ID.out ./runs/arrayruns135.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/136_\$TASK_ID.err -o /home/atzmonm/data/runs/136_\$TASK_ID.out ./runs/arrayruns136.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/137_\$TASK_ID.err -o /home/atzmonm/data/runs/137_\$TASK_ID.out ./runs/arrayruns137.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/138_\$TASK_ID.err -o /home/atzmonm/data/runs/138_\$TASK_ID.out ./runs/arrayruns138.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/139_\$TASK_ID.err -o /home/atzmonm/data/runs/139_\$TASK_ID.out ./runs/arrayruns139.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/140_\$TASK_ID.err -o /home/atzmonm/data/runs/140_\$TASK_ID.out ./runs/arrayruns140.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/141_\$TASK_ID.err -o /home/atzmonm/data/runs/141_\$TASK_ID.out ./runs/arrayruns141.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/142_\$TASK_ID.err -o /home/atzmonm/data/runs/142_\$TASK_ID.out ./runs/arrayruns142.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/143_\$TASK_ID.err -o /home/atzmonm/data/runs/143_\$TASK_ID.out ./runs/arrayruns143.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/144_\$TASK_ID.err -o /home/atzmonm/data/runs/144_\$TASK_ID.out ./runs/arrayruns144.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/145_\$TASK_ID.err -o /home/atzmonm/data/runs/145_\$TASK_ID.out ./runs/arrayruns145.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/146_\$TASK_ID.err -o /home/atzmonm/data/runs/146_\$TASK_ID.out ./runs/arrayruns146.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/147_\$TASK_ID.err -o /home/atzmonm/data/runs/147_\$TASK_ID.out ./runs/arrayruns147.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/148_\$TASK_ID.err -o /home/atzmonm/data/runs/148_\$TASK_ID.out ./runs/arrayruns148.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/149_\$TASK_ID.err -o /home/atzmonm/data/runs/149_\$TASK_ID.out ./runs/arrayruns149.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/150_\$TASK_ID.err -o /home/atzmonm/data/runs/150_\$TASK_ID.out ./runs/arrayruns150.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/151_\$TASK_ID.err -o /home/atzmonm/data/runs/151_\$TASK_ID.out ./runs/arrayruns151.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/152_\$TASK_ID.err -o /home/atzmonm/data/runs/152_\$TASK_ID.out ./runs/arrayruns152.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/153_\$TASK_ID.err -o /home/atzmonm/data/runs/153_\$TASK_ID.out ./runs/arrayruns153.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/154_\$TASK_ID.err -o /home/atzmonm/data/runs/154_\$TASK_ID.out ./runs/arrayruns154.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/155_\$TASK_ID.err -o /home/atzmonm/data/runs/155_\$TASK_ID.out ./runs/arrayruns155.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/156_\$TASK_ID.err -o /home/atzmonm/data/runs/156_\$TASK_ID.out ./runs/arrayruns156.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/157_\$TASK_ID.err -o /home/atzmonm/data/runs/157_\$TASK_ID.out ./runs/arrayruns157.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/158_\$TASK_ID.err -o /home/atzmonm/data/runs/158_\$TASK_ID.out ./runs/arrayruns158.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/159_\$TASK_ID.err -o /home/atzmonm/data/runs/159_\$TASK_ID.out ./runs/arrayruns159.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/160_\$TASK_ID.err -o /home/atzmonm/data/runs/160_\$TASK_ID.out ./runs/arrayruns160.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/161_\$TASK_ID.err -o /home/atzmonm/data/runs/161_\$TASK_ID.out ./runs/arrayruns161.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/162_\$TASK_ID.err -o /home/atzmonm/data/runs/162_\$TASK_ID.out ./runs/arrayruns162.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/163_\$TASK_ID.err -o /home/atzmonm/data/runs/163_\$TASK_ID.out ./runs/arrayruns163.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/164_\$TASK_ID.err -o /home/atzmonm/data/runs/164_\$TASK_ID.out ./runs/arrayruns164.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/165_\$TASK_ID.err -o /home/atzmonm/data/runs/165_\$TASK_ID.out ./runs/arrayruns165.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/166_\$TASK_ID.err -o /home/atzmonm/data/runs/166_\$TASK_ID.out ./runs/arrayruns166.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/167_\$TASK_ID.err -o /home/atzmonm/data/runs/167_\$TASK_ID.out ./runs/arrayruns167.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/168_\$TASK_ID.err -o /home/atzmonm/data/runs/168_\$TASK_ID.out ./runs/arrayruns168.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/169_\$TASK_ID.err -o /home/atzmonm/data/runs/169_\$TASK_ID.out ./runs/arrayruns169.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/170_\$TASK_ID.err -o /home/atzmonm/data/runs/170_\$TASK_ID.out ./runs/arrayruns170.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/171_\$TASK_ID.err -o /home/atzmonm/data/runs/171_\$TASK_ID.out ./runs/arrayruns171.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/172_\$TASK_ID.err -o /home/atzmonm/data/runs/172_\$TASK_ID.out ./runs/arrayruns172.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/173_\$TASK_ID.err -o /home/atzmonm/data/runs/173_\$TASK_ID.out ./runs/arrayruns173.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/174_\$TASK_ID.err -o /home/atzmonm/data/runs/174_\$TASK_ID.out ./runs/arrayruns174.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/175_\$TASK_ID.err -o /home/atzmonm/data/runs/175_\$TASK_ID.out ./runs/arrayruns175.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/176_\$TASK_ID.err -o /home/atzmonm/data/runs/176_\$TASK_ID.out ./runs/arrayruns176.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/177_\$TASK_ID.err -o /home/atzmonm/data/runs/177_\$TASK_ID.out ./runs/arrayruns177.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/178_\$TASK_ID.err -o /home/atzmonm/data/runs/178_\$TASK_ID.out ./runs/arrayruns178.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/179_\$TASK_ID.err -o /home/atzmonm/data/runs/179_\$TASK_ID.out ./runs/arrayruns179.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/180_\$TASK_ID.err -o /home/atzmonm/data/runs/180_\$TASK_ID.out ./runs/arrayruns180.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/181_\$TASK_ID.err -o /home/atzmonm/data/runs/181_\$TASK_ID.out ./runs/arrayruns181.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/182_\$TASK_ID.err -o /home/atzmonm/data/runs/182_\$TASK_ID.out ./runs/arrayruns182.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/183_\$TASK_ID.err -o /home/atzmonm/data/runs/183_\$TASK_ID.out ./runs/arrayruns183.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/184_\$TASK_ID.err -o /home/atzmonm/data/runs/184_\$TASK_ID.out ./runs/arrayruns184.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/185_\$TASK_ID.err -o /home/atzmonm/data/runs/185_\$TASK_ID.out ./runs/arrayruns185.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/186_\$TASK_ID.err -o /home/atzmonm/data/runs/186_\$TASK_ID.out ./runs/arrayruns186.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/187_\$TASK_ID.err -o /home/atzmonm/data/runs/187_\$TASK_ID.out ./runs/arrayruns187.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/188_\$TASK_ID.err -o /home/atzmonm/data/runs/188_\$TASK_ID.out ./runs/arrayruns188.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/189_\$TASK_ID.err -o /home/atzmonm/data/runs/189_\$TASK_ID.out ./runs/arrayruns189.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/190_\$TASK_ID.err -o /home/atzmonm/data/runs/190_\$TASK_ID.out ./runs/arrayruns190.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/191_\$TASK_ID.err -o /home/atzmonm/data/runs/191_\$TASK_ID.out ./runs/arrayruns191.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/192_\$TASK_ID.err -o /home/atzmonm/data/runs/192_\$TASK_ID.out ./runs/arrayruns192.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/193_\$TASK_ID.err -o /home/atzmonm/data/runs/193_\$TASK_ID.out ./runs/arrayruns193.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/194_\$TASK_ID.err -o /home/atzmonm/data/runs/194_\$TASK_ID.out ./runs/arrayruns194.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/195_\$TASK_ID.err -o /home/atzmonm/data/runs/195_\$TASK_ID.out ./runs/arrayruns195.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/196_\$TASK_ID.err -o /home/atzmonm/data/runs/196_\$TASK_ID.out ./runs/arrayruns196.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/197_\$TASK_ID.err -o /home/atzmonm/data/runs/197_\$TASK_ID.out ./runs/arrayruns197.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/198_\$TASK_ID.err -o /home/atzmonm/data/runs/198_\$TASK_ID.out ./runs/arrayruns198.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/199_\$TASK_ID.err -o /home/atzmonm/data/runs/199_\$TASK_ID.out ./runs/arrayruns199.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/200_\$TASK_ID.err -o /home/atzmonm/data/runs/200_\$TASK_ID.out ./runs/arrayruns200.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/201_\$TASK_ID.err -o /home/atzmonm/data/runs/201_\$TASK_ID.out ./runs/arrayruns201.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/202_\$TASK_ID.err -o /home/atzmonm/data/runs/202_\$TASK_ID.out ./runs/arrayruns202.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/203_\$TASK_ID.err -o /home/atzmonm/data/runs/203_\$TASK_ID.out ./runs/arrayruns203.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/204_\$TASK_ID.err -o /home/atzmonm/data/runs/204_\$TASK_ID.out ./runs/arrayruns204.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/205_\$TASK_ID.err -o /home/atzmonm/data/runs/205_\$TASK_ID.out ./runs/arrayruns205.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/206_\$TASK_ID.err -o /home/atzmonm/data/runs/206_\$TASK_ID.out ./runs/arrayruns206.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/207_\$TASK_ID.err -o /home/atzmonm/data/runs/207_\$TASK_ID.out ./runs/arrayruns207.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/208_\$TASK_ID.err -o /home/atzmonm/data/runs/208_\$TASK_ID.out ./runs/arrayruns208.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/209_\$TASK_ID.err -o /home/atzmonm/data/runs/209_\$TASK_ID.out ./runs/arrayruns209.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/210_\$TASK_ID.err -o /home/atzmonm/data/runs/210_\$TASK_ID.out ./runs/arrayruns210.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/211_\$TASK_ID.err -o /home/atzmonm/data/runs/211_\$TASK_ID.out ./runs/arrayruns211.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/212_\$TASK_ID.err -o /home/atzmonm/data/runs/212_\$TASK_ID.out ./runs/arrayruns212.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/213_\$TASK_ID.err -o /home/atzmonm/data/runs/213_\$TASK_ID.out ./runs/arrayruns213.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/214_\$TASK_ID.err -o /home/atzmonm/data/runs/214_\$TASK_ID.out ./runs/arrayruns214.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/215_\$TASK_ID.err -o /home/atzmonm/data/runs/215_\$TASK_ID.out ./runs/arrayruns215.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/216_\$TASK_ID.err -o /home/atzmonm/data/runs/216_\$TASK_ID.out ./runs/arrayruns216.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/217_\$TASK_ID.err -o /home/atzmonm/data/runs/217_\$TASK_ID.out ./runs/arrayruns217.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/218_\$TASK_ID.err -o /home/atzmonm/data/runs/218_\$TASK_ID.out ./runs/arrayruns218.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/219_\$TASK_ID.err -o /home/atzmonm/data/runs/219_\$TASK_ID.out ./runs/arrayruns219.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/220_\$TASK_ID.err -o /home/atzmonm/data/runs/220_\$TASK_ID.out ./runs/arrayruns220.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/221_\$TASK_ID.err -o /home/atzmonm/data/runs/221_\$TASK_ID.out ./runs/arrayruns221.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/222_\$TASK_ID.err -o /home/atzmonm/data/runs/222_\$TASK_ID.out ./runs/arrayruns222.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/223_\$TASK_ID.err -o /home/atzmonm/data/runs/223_\$TASK_ID.out ./runs/arrayruns223.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/224_\$TASK_ID.err -o /home/atzmonm/data/runs/224_\$TASK_ID.out ./runs/arrayruns224.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/225_\$TASK_ID.err -o /home/atzmonm/data/runs/225_\$TASK_ID.out ./runs/arrayruns225.csh
qsub -q "all2.q" -e /home/atzmonm/data/runs/226_\$TASK_ID.err -o /home/atzmonm/data/runs/226_\$TASK_ID.out ./runs/arrayruns226.csh